### PR TITLE
Support query parameters and responses

### PR DESCRIPTION
**Pull request by herophuong**
Any comment for new code is welcome!

### CODE REVIEW

**Comment by kevinrenskers** [comment]
Thank you for the pull request, awesome work. However, can you fix a couple of things? Most importantly there are some weird spacing issues in the generated markdown file, for example `**get**:   find an account`. 

The other thing is code style. Can use use single quotes for strings, triple equal marks and always use braces for if statements? Thanks!

**Comment by herophuong** [comment]
More clean-ups for you! That should fix above problems.
OT: IMO, handlebars + markdown = horrible mess

**Comment by kevinrenskers** [comment]
Thanks! And yes, handlebars generating markdown isn't great, totally agree. Do you have a suggestion for a different template language that would work better?

**Comment by kevinrenskers** [comment]
Sadly your PR is to the master branch instead of develop (the README). No huge problem, I think I'll merge this tonight, test, and release.

**Comment by herophuong** [comment]
Thanks. Noted for next contribution!

**Comment by kevinrenskers** [comment]
Sorry for the long wait. Basically I'm not really in love with the added code: _indent takes an indentation level but _addSpacesBeforeLine takes actual spaces. Something like `{{{addSpacesBeforeLine example 28 true}}}{{/each}}{{/if}}` is kind of hard to maintain, which will be my job going forward.

Why not use actual indentation in the template instead of these 2 helper methods? Or if that's not possible (it should!) can you make these methods similar at least? It would also be great if you could resubmit the fixes to the develop branch.

**Comment by smazurov** [comment]
I think query/uri params should be represented as a table:

### Uri Parameters
| param | type                 | example | description            |
| ----- |:--------------------:| ------- | -----------------------|
| id    | integer              | `123`   | the id of the resource |
| type  | one of (food, drink) | `food`  | type of recipe         |

### Query Parameters

| param    | type    | example | description     |
| ---------|:-------:| ------- | --------------- |
| page     | integer | `123`   | page number     |
| category | string  | `cake`  | category filter |

code:
```md
### Uri Parameters
| param | type                 | example | description            |
| ----- |:--------------------:| ------- | -----------------------|
| id    | integer              | `123`   | the id of the resource |
| type  | one of (food, drink) | `food`  | type of recipe         |

### Query Parameters

| param    | type    | example | description     |
| ---------|:-------:| ------- | --------------- |
| page     | integer | `123`   | page number     |
| category | string  | `cake`  | category filter |
```

**Comment by kevinrenskers** [comment]
Tables are not standard markdown though, and not easily human readable in their unrendered form. This should generate quite simple markdown files, not full documentation.

**Comment by smazurov** [comment]
arguably spending 4 bullet points per query parameter is less compact. Ditto on tables not being "standard", but I'd say 90% of use cases cover it (with github alone). Ideally its a config switch `--params=table,list,none`

**Comment by herophuong** [comment]
Let me explain a bit about those 2 helpers:
`addSpacesBeforeLine`: add spaces before **each line**. Because the example can span multiple lines, I need to add spaces before all of them to make sure that the next bullet, or number in the list will be correctly recognized as part of the list.
`indent`: this is written because the mix of handlebarjs and markdown really makes me headache and eyeache to debug the indentation. When the indentation get multiple levels down, it will be very hard to know what is nested under what.

I will remake the `addSpacesBeforeLine` to `addIndentationBeforeLine` for consistency as you suggest. Or we should rename it to `mergeIndentation` and `addIndentation`?

Also you are right about the table format. That is much better for query parameters.

You can give some final comment and close this pull request. I will make new one into `develop` branch.

**Comment by kevinrenskers** [comment]
addIndentationBeforeLine would be better, yes. Please don't do the query params as a table in the same pull request. Separate PRs would be better as I want to test that separately. Thanks!

**Comment by kevinrenskers** [comment]
I do agree about the 4 bullet points per query param, it's too much. In raml2html it's written more like a sentence. Please check out that project's example file.

**Comment by kevinrenskers** [comment]
Better yet check out its item template as it also handles enums and stuff: https://github.com/kevinrenskers/raml2html/blob/master/lib/item.handlebars

**Pull request closed without merging**
